#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TOOLS_PATH="${DIR}/.."

# Подключаем файл настроек
if [[ -f "${TOOLS_PATH}/deploy_settings/base.ini" ]]; then
    . ${TOOLS_PATH}/deploy_settings/base.ini
    if [[ -f "${TOOLS_PATH}/deploy_settings/${ENV_TYPE}.ini" ]]; then
        . ${TOOLS_PATH}/deploy_settings/${ENV_TYPE}.ini
    else
        echo "Файл настроек для зоны не найден"
        exit 25
    fi
else
    echo "Файл настроек не найден"
    exit 25
fi
PROJECT_PATH_FULL="${DIR}${PROJECT_PATH}"

# подключаем телеграм чат
#. ./lib/telegram

cd ${PROJECT_PATH_FULL}
#send_telegram_message "начато обновление зоны ${ENV_TYPE}";
echo "Получение изменений из git"
git pull -q -v origin ${GIT_BRANCH}
# сделать проверку на ошибки из гита
echo "Изменения из git получены"
echo "======"

cd ${COMPOSER_DIRECTORY}
if [[ ! -f "composer.phar" ]]; then
    echo "не найден файл composer"
    echo "======"
    exit 25
fi
if [[ -f "composer.phar" && -f "composer.json" ]]; then
    echo "начало установки пакетов из composer"
    if [[ "${ENV_TYPE}" = "dev" ]]; then
        ${PHP_PATH} -d memory_limit=1024M composer.phar install
    else
        ${PHP_PATH} -d memory_limit=1024M composer.phar install --no-dev
    fi
    # добавить проверку на ошибки
    echo "Установка пакетов из composer завершена"
    echo "======"
fi

cd ${DIR}
if [[ -f "${DIR}${MIGRATE_PATH}" ]] && ( [[ -d "${PROJECT_PATH_FULL}/local/modules/${MIGRATE_MODULE_NAME}" ]] || [[ -d "${PROJECT_PATH_FULL}bitrix/modules/${MIGRATE_MODULE_NAME}" ]] ); then
    echo "начало миграций"
    ${PHP_PATH} ${MIGRATE_PATH} ${PROJECT_PATH_FULL}
    # добавить проверку на ошибки
    echo "Миграции установлены"
    echo "======"
fi
if [[ "${ENV_TYPE}" = "prod" ]]; then
    git remote prune origin
    echo "Очистка git завершена"
    echo "======"
fi
#send_telegram_message "обновление зоны ${ENV_TYPE} завершено успешно";