#!/usr/bin/env php
<?php


$localPath = realpath(__DIR__ . '/..');
$toolPath = $localPath.'/modules/sprint.migration/tools/migrate.php';
if(file_exists($toolPath)) {
    require_once $toolPath;
} else {
    $bitrixPath = realpath($localPath.'/../bitrix');
    $toolPath = $bitrixPath.'/modules/sprint.migration/tools/migrate.php';
    if(file_exists($toolPath)) {
        require_once $toolPath;
    }
}